package models;

public enum Actions {
    GET_ANNOUNCEMENTS,
    GET_CARTYPES,
    GET_CARBODIES,
    GET_CARBRANDS,
    GET_CARMODELS,
    GET_CARPHOTOS,
    GET_CARENGINES,
    GET_SELLERCONTACS,
    ADD_ANNOUNCEMENTS,
    EDIT_ANNOUNCEMENTS,
    ADD_SELLERCONTACT,
    DELETE_SELLERCONTACT,
    ADD_CARPHOTO,
    DELETE_CARPHOTO
}
